### ISSUE TITLE
Initializing the camera object: camera = GoProHero([ip, password, loglevel])

### ISSUE THREAD

**Issue by RemPsyc** [joshvillbrandt/goprohero#12]
Hello,

What should we enter for the GoPro Hero (4 Black) loglevel when creating the camera instance? I'm following the instructions from http://goprohero.readthedocs.org/en/latest/API/ and I tried in the Raspbian LXTerminal: camera = GoProHero(10.5.5.9, gorazlab, 1), without success: bash: syntax error near unexpected token '('. Furthermore, 'from goprohero import GoProHero' gives 'from: can't read /var/mail/goprohero'.

Thanks for any help with this,

**Comment by keerthanamanivannan** [comment]
Hi, did you ever figure out where to create the camera instance?

**Comment by joshvillbrandt** [comment]
Hmm. Is "goprohero" actually installed? Does this work for you for HERO3 cameras?

I'm unfamiliar with the LXTerminal. I'm not sure how that might be changing things.

**Comment by keerthanamanivannan** [comment]
Hi, I'm using a GoPro Hero4 Session, the latest one. Does goprohero work with that?

**Comment by joshvillbrandt** [comment]
Not sure! I haven't tried one of those cameras.

**Comment by RemPsyc** [comment]
For your information, we decided to give up on using the GoPros for our project because of the technical challenges they entail and also because of the excessive latency of the cameras.

Rémi

On Jul 11, 2016, at 1:13 PM, "Josh Villbrandt" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure! I haven't tried one of those cameras.

-

**Comment by joshvillbrandt** [comment]
Roger. Thanks!
