### ISSUE TITLE
Hero 3 in RC Mode

### ISSUE THREAD

**Issue by tnk3r** [joshvillbrandt/goprohero#15]
Is there a way to communicate with Hero3 in RC mode? I can't resolve gopro.status() without exception.

 Hero4 works pretty well in RC mode, I cant change vidres or fps, but I am primarily using wifi for status indications. To keep gopro's automated and in sequence.

**Comment by joshvillbrandt** [comment]
Hi @x86box,

You are referring to the "remote control" aka infrastructure mode, correct? I believe the "app" aka ad-hoc mode API is not available with in the "remote control" mode. This is obviously another method of communication that the remote control is using, however I don't have the details on how that method works. From the functionality present on the remote control, it appears that this information available in this mode is much more limited.

Best of luck!

Josh

**Comment by x86box** [comment]
At least for now, Hero 4 has many functions implemented in this mode. 

My next step is trying to start webserver from an autoexec.ash.
