### ISSUE TITLE
Hero4 Session

### ISSUE THREAD

**Issue by francisra** [joshvillbrandt/goprohero#18]
Hello.

First of all, thank you for sharing your valuable work!. I own a Hero4 session camera and a pretende to control it remotely via wifi. I am using your goprohero library. I am facing some troubles with wifi connection.
First, I am trying to get familiar with API using goprctl command line interface.

The camera is has the wifi enabled, but I can only connect to he camera during the 3 minutes window of the "add new app" proccess. When the camera stops the pairing proccess tcp/ip connection goes down. 
If I turn the camera in sleep mode, inspite of being connected to the camera essid , the camera doesnt respond again until I start a new pairing app proccess...

Is this a particular behavior of Hero 4 Session?. Do I omitted some step? Am I doing something wrong?

Francis.

**Comment by chamoladri** [comment]
uno de los principales problemas que yo encontré cuando usaba esta
librería era que la cámara debía estar conectada por wifi directamente a la
computadora que la controlaba  es decir no podía estar conectada a través
de una red o un router . hay que establecer una coneccion directa
(Computadora -Gopro) .

Siempre use esta libreria con gopro Black 3+  no con gopro Heroe 4 .

Saludos !


2016-01-28 6:10 GMT-03:00 francisra <notifications@github.com>:

**Comment by joshvillbrandt** [comment]
Hi Francis,

This library has been primarily tested against Hero3 cameras. I've done some minimal testing (power on/off) with a regular Hero4 camera, but unfortunately do not have a Hero4 session camera to test with. I hear the Hero4 cameras utilize at least parts of the API represented here, but the new cameras also expose a newer API. (Google leads me to [this API](https://github.com/citolen/goproh4/blob/master/GP4-API.json) specifically for the Hero4.)

Best of luck finding something that works!

Josh
