### ISSUE TITLE
Hero4 pairing procedure

### ISSUE THREAD

**Issue by McKracken** [joshvillbrandt/goprohero#24]
Hi, 
the issue I'm reporting may not be directly linked with these APIs.
I bought a Hero4 few weeks ago, and I'm having a problem using this library. The problem arises from the fact that to be connected to the Hero4 wifi from another device, a pairing procedure is required. Such procedure is performed when you first connect the camera to a mobile device with GoPro App, that requires to insert the pairing code shown by the camera.
Now, I can connect to the Camera Wifi from my macbook (I suppose it's the same with any other laptop, I haven't tried with others yet), but of course I'm not asked for any code. The camera keeps staying in the "Waiting for pairing" state, showing the code to be inserted on the connected device. At this stage, if I try to send a command through the goprohero library, e.g. 
```
camera = GoProHero(password="goprohero")
camera.command('record','on')
```
it results in a successful message, but the camera disconnect the wifi as it receives a request over the wifi without having completed the pairing procedure. Of course, no action is performed by the GoPro (apart from disconnecting the wifi).
I don't know if this is due to an update in the firmware of the Hero4, as probably this issue wasn't considered while this library was built, and therefore (to the best of my understanding) there's no way to pair the GoPro through the library.
Anyone has any hint about that?

Cheers

**Comment by KonradIT** [comment]
Hi. you need to have the camera already paired to the app in wifi app mode.

**Comment by McKracken** [comment]
Are you saying that I need to pair it to a mobile device, also if I want to work with it from a laptop? 
As long as I could see there's no proprietary application to be used on a laptop (there are others that you can pay, and might pair the device with the laptop, but a "for free" solution would be better).

**Comment by KonradIT** [comment]
Once you pair the camera to the GoPro mobile app you don't need a pairing code. Just turn the WiFi and connect to laptop.

**Comment by KonradIT** [comment]
I'm adding camera pairing to my API ([gopro-py-api](http://github.com/konradit/gopro-py-api)), when I get it working I'll add it here too.

**Comment by KonradIT** [comment]
Hey @McKracken and @joshvillbrandt :

I figured how to pair my camera to my PC, take a look:

You put the camera in pairing mode, that is, go to settings > Wifi > turn it on > PAIR > Gopro App. Then a code will show (4 numbers).

Connect your computer to the wifi AP which is GPXXXXXX and the password is "goprohero", then use whatever python library to trigger these URLs:

>https://10.5.5.9/gpPair?c=start&pin=CODE&mode=0

Replace the "CODE" with the code shown in the front display.

This will print a password, make sure your camera is still connected to your computer. 

Make sure you deal with SSL certificates in here.

Now on to setup:

>http://10.5.5.9/gp/gpControl/command/wireless/ap/ssid?ssid=GOPRONAME&pw=GOPROPASS

You will need to setup a name and password for your GoPro, so decide (see online for the name and password length and character restrinctions).

>https://10.5.5.9/gpPair?c=finish&pin=CODE&mode=0

And then finish the pairing process. This will set the camera to the new name and password so make sure to connect to it before proceeding.

Here is how I am doing this: https://github.com/KonradIT/gopro-py-api/blob/master/goprocam/GoProCamera.py#L364

**Comment by McKracken** [comment]
Thank you very much @KonradIT ! I was just about to discover this myself with a little bit of Wireshark and others. You saved me half a day of work! Maybe if I have time, I might integrate this passage in the library if @joshvillbrandt allows that, or is not willing to do it himself!
Thank you again!

**Comment by joshvillbrandt** [comment]
@McKracken I'm not contributing new code to this repo myself right now, but I'm happy to review a pull request.

Thanks for the assistance, @KonradIT!

I'll close this for now since it seems to core issue is resolved.
