### ISSUE TITLE
Datetime of GoPro

### ISSUE THREAD

**Issue by DenisCarriere** [joshvillbrandt/goprohero#5]
Being able to sync your GoPro with your computer can be tricky since you don't know the seconds on the GoPro, only the minutes are displayed on the screen.

Would be nice to have an attribute added to the `status` that would have the a datetime object called `datetime` when the status is called.

It comes in handy when you are trying to sync a GPX track with the GoPro's photos/videos.

```python
>>> c = GoProHero()
>>> c.status()
{...
'datetime': '2014-11-30T22:09:40'
}
```

**Comment by joshvillbrandt** [comment]
Since I wasn't able to find anything that resembled a date string, I'm closing this as not possible - at least not for the GoPro 2, 3, and 3+ endpoints that I know about. Feel free to reopen if you think you've found something.

Thanks!
