### ISSUE TITLE
Set wireless interface

### ISSUE THREAD

**Issue by thijsvdanker** [joshvillbrandt/goprohero#6]
The [GoProController](https://github.com/joshvillbrandt/GoProController) allows you to set a different network interface through an environment variable.
```
env GOPRO_WIFI_INTERFACE=wlan1
```
It would be nice if `goproctl` allowed you to either set it in the parameters or use (the same?) env variable.

**Comment by joshvillbrandt** [comment]
This was added in 92db6cafddfccf2b3caaa3769d90246a68d0d0e8.
